#+REVEAL_ROOT: file:///home/anarcroth/reveal.js
#+REVEAL_THEME: moon
#+REVEAL_TRANS: zoom
#+REVEAL_SPEED: 0.5
#+Title: What is Open Source
#+OPTIONS: reveal_slide_number:h/v num:nil

* Free as in Freedom

#+BEGIN_NOTES
Many people, when they hear "Open Source", they think - "Oh, that's just free software", or "That's software that you can see the source code and you can distribute it". Although this is technically correct, to the extend we use it on a day-to-day basis, there is something much deeper behind the idea of *Open Source*. It's not just about being able to see how someone implemented something, or just getting software for free, it's about what that symbolizes, what it means to be free, what it means to have control over what you are doing. It means that you are a part of a moral movement, that tries to make the world better.

The Linux kernel isn't just simply free, it *gives you freedom*. You, the user, have the freedom to choose, what you want, what you can have, what you are agreeing to. There are plenty of things in life that are simply "free of charge", but just a few things give you moral freedom.

Let's take a walk down memory lane (in a time when we weren't born and things were much more UNIX like :P) and see how Open Source began. And, hopefully, by the end, you will see the significance of it!
#+END_NOTES

* This is me

- email: mdn150@aubg.edu
- Linux user, git lover, typing enthusiast

[kbpic]()

* Once upon a time

There was a great philosopher and a great engineer.

#+REVEAL: split

The philosopher

[rms]()

#+BEGIN_NOTES
Once upon a time, there was darkness... A world filled with Microsoft labels, lawyers, bugs, legal contracts, and dirty money. **DISCLAIMER**: These are all jokes and pokes towards Microsoft, I don't mean this to be a circle-jerk of GNU/Linux people. Then a bearded man came. And much like all great bearded people, he was not found of how the world of software was stated. He was constrained be proprietary software that had bugs and didn't want to have an open community. So he was in front of a moral dilemma - should he use software that didn't cherish the freedom of the user? That's why he made a decision, to create his own operating system, which he would distribute openly, invite other people to use it, this solving the dilemma of having to choose between closed, "malicious" software. And thus, the GNU Operating System was born.
#+END_NOTES

* The GNU Operating System

#+BEGIN_NOTES
On the zeroth day God created a compiler, something that would transform human readable code into something that the machine would understand . On day one, he created a debugger, a tool which helped the programmer to find bugs, and see in what state is the program in any given time. On day two, he created the best text editor in the world. Then for the rest of the days, one by one, each program that was needed to be written, in order for an Operating System to exit, was created. In the end only one thing was missing - a kernel, the thing that allocates resources and reads from the disk, in order for other programs to work properly.
#+END_NOTES

* The Linux kernel

#+BEGIN_NOTES
The Linux kernel was just a good operating system. It did what it needed to do, through the tried and true method, of being a monolith that provided an area where all the other programs can collaborate and work together. In the beginning, maybe, the most important thing was having a C-compiler, which allowed for more work to be done.
#+END_NOTES

* What about the market?

#+BEGIN_NOTES
Because all of these things were actually given out for free, as in, no money, this was something completely different for the time. Well, not exactly. Before Microsoft came and predominated the world with the idea about proprietary software, people just shared code to one another, but after the lawyers flooded the stage, business changed. So how does the idea about open software compares to the needs of the user?

The thing is that, for the needs of the market, people either had the choice to pay a license and get support form a monopoly, i.e. some company that owned the code, or they could invest in some open source project and have many, many people be able to help and improve the product as it develops. Of course, since that was a high risk tactic, not a lot of people were ready to take on it. The first company that really invested into open source was called *CYGNUS*.

But even with the help and funding of CYGNUS, the market was still struggling with these independent hackers. This is where Netscape comes into play. Netscape was the first major company that released it's software out in the open. It became - Open Source.

But an important distinction must be made. Open Source doesn't mean "public domain". The public domain means that anyone can get something, tinker with it, create something that is proprietary and we are at square one. The public domain doesn't maintain the sate of having "freedom". And nothing is more important than being free.
#+END_NOTES

* The GPL

#+BEGIN_NOTES
So the way we deal with this is through the most important license that was ever made - The GNU General Public License. This license actually tells you, and if you read it you will see, that you can get a copy, distribute, modify, sell and make a profit, from the hereby presented software, but you cannot hinder any of these capabilities, once you get the software. What this means is that, this license allows you to distribute an open product that allows you to choose what you are getting, allows you to see what you can do with it, no hidden stuff, no shenanigans.

There are thousands of products that are licensed under this, even the Linux kernel is one such example. It may not be the most elegant license, but it sure is important.
#+END_NOTES

* The amazing world of Open Source

#+BEGIN_NOTES
Throughout the years, Open Source has managed to create an amazing community, filled with hackers who want to be part of a moral movement and make something useful. We want to help and get out brilliant idea out there so it can do something. We want to fix things.

There are so many things that are open source, that we use today, that we are not aware of. The whole software world works because of open software. We cannot live without it. And we know that's the case because we cannot see it. It's not obvious because it's doing its job so well, that we don't need to notice it.

Here are some examples - Mozilla Firefox is Open Source, so is the Linux Kernel, together with the thousand distributions it comes with, VIM, Emacs, and Git are also Open Source... So are all of the libraries that come from the Apache foundation, OpenSSL, cryptographic libraries, with which we make sure that our connections (through which we make business), libraries with which we analyze data, gather data, create medical software that cures people, software that connects people together, software that allows for planes to fly, ships to ship, and cars to car (Tesla are releasing their kernel as well!). Our phones use open source, our PCs, MACs, vending machines... Yes they are not all 100% open and free, but they do rely on this community. We are this community, we are the hackers that make the world work.
#+END_NOTES
