#+REVEAL_ROOT: file:///home/anarcroth/reveal.js
#+REVEAL_THEME: moon
#+REVEAL_TRANS: zoom
#+REVEAL_SPEED: 0.5
#+Title: What is Open Source
#+OPTIONS: reveal_slide_number:h/v num:nil

* Free as in Freedom

#+BEGIN_NOTES
Many people, when they hear "Open Source", they think - "Oh, that's just free software", or "That's software that you can see the source code and you can distribute it". Although this is technically correct, to the extend we use it on a day-to-day basis, there is something much deeper behind the idea of *Open Source*. It's not just about being able to see how someone implemented something, or just getting software for free, it's about what that symbolizes, what it means to be free, what it means to have control over what you are doing. It means that you are a part of a moral movement, that tries to make the world better.

The Linux kernel isn't just simply free, it *gives you freedom*. You, the user, have the freedom to choose, what you want, what you can have, what you are agreeing to. There are plenty of things in life that are simply "free of charge", but just a few things give you moral freedom.

Let's take a walk down memory lane (in a time when we weren't born and things were much more UNIX like :P) and see how Open Source began. And, hopefully, by the end, you will see the significance of it!
#+END_NOTES

* This is me

- email: mdn150@aubg.edu
- Linux user, git lover, typing enthusiast

[kbpic]()

* Once upon a time

There was a great philosopher and a great engineer.

#+REVEAL: split

The philosopher

[rms]()

#+BEGIN_NOTES
Once upon a time, there was darkness... A world filled with Microsoft labels, lawyers, bugs, legal contracts, and dirty money. **DISCLAIMER**: These are all jokes and pokes towards Microsoft, I don't mean this to be a circle-jerk of GNU/Linux people. Then a bearded man came. And much like all great bearded people, he was not found of how the world of software was stated. He was constrained be proprietary software that had bugs and didn't want to have an open community. So he was in front of a moral dilemma - should he use software that didn't cherish the freedom of the user? That's why he made a decision, to create his own operating system, which he would distribute openly, invite other people to use it, this solving the dilemma of having to choose between closed, "malicious" software. And thus, the GNU Operating System was born.
#+END_NOTES

* The GNU Operating System

#+BEGIN_NOTES
On the zeroth day God created a compiler, something that would transform human readable code into something that the machine would understand . On day one, he created a debugger, a tool which helped the programmer to find bugs, and see in what state is the program in any given time. On day two, he created the best text editor in the world. Then for the rest of the days, one by one, each program that was needed to be written, in order for an Operating System to exit, was created. In the end only one thing was missing - a kernel, the thing that allocates resources and reads from the disk, in order for other programs to work properly.
#+END_NOTES

* The Linux kernel

#+BEGIN_NOTES

#+END_NOTES

* RMS and Torvalds

#+BEGIN_NOTES

#+END_NOTES

* The GPL

#+BEGIN_NOTES

#+END_NOTES

* The amazing world of Open Source

#+BEGIN_NOTES

#+END_NOTES
